// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6hxaVYi8eEZQgTMTBFlHBYr1aXGrFuM',
    appId: '1:685026869006:web:d6f70cf2cd38500c32e15f',
    messagingSenderId: '685026869006',
    projectId: 'ffbb-7f33d',
    authDomain: 'ffbb-7f33d.firebaseapp.com',
    storageBucket: 'ffbb-7f33d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKDyBZHrupvWi9_RnUFJReOpOZ_hdWt4',
    appId: '1:685026869006:android:4917ae2d11027e8c32e15f',
    messagingSenderId: '685026869006',
    projectId: 'ffbb-7f33d',
    storageBucket: 'ffbb-7f33d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IH4hdTh0tRgzbnbrEYfKW5F3wLBb8Qg',
    appId: '1:685026869006:ios:26b56e104278153332e15f',
    messagingSenderId: '685026869006',
    projectId: 'ffbb-7f33d',
    storageBucket: 'ffbb-7f33d.appspot.com',
    iosBundleId: 'com.dev.firebase',
  );
}
